bill/urls.py
from django.conf.urls import patterns,include,url
from bill.views import *

urlpatterns=patterns('',
                     url(r'^$',BookingView.as_view(success_url="/mypage/mybookings/"),name='booking'),
                     url(r'^conf/(?P<booking_id>[-0-9]+)/$',ConfirmtheBookingView,name='conf'),
                     url(r'^conf/(?P<booking_id>[-0-9]+)/valid/$',ValidBooking,name='valid'),
                     url(r'^conf/(?P<booking_id>[-0-9]+)/delete/$',DeleteBooking,name='delete'),
                     url(r'^room/(?P<sdate>[-0-9]+)/(?P<edate>[-0-9]+)/$',FindFreeRoom,name='freeroom'),
                     url(r'^room/(?P<sdate>[-0-9]+)/(?P<edate>[-0-9]+)/(?P<style>[a-z]+)/$',FindFreeRoomWS,name='freeroomws'),
                     url(r'^service/$',ServiceOrderView.as_view(success_url="/mypage/myservices/"),name='serviceorder'),
                     url(r'^service/list/$',servicelist,name='servicelist'),
                     url(r'^confservice/(?P<serviceorder_id>[-0-9]+)/$',ConfirmetheServiceOrderView,name='confservice'),
                     url(r'^confservice/(?P<serviceorder_id>[-0-9]+)/valid/$',ValidServiceOrder,name='validservice'),
                     url(r'^confservice/(?P<serviceorder_id>[-0-9]+)/delete/$',DeleteServiceOrder,name='deleteservice'),
                     url(r'^room/(?P<housing>[0-9]+)/(?P<floor>[0-9]+)/(?P<number>[0-9]+)/$',roomdetail,name='roomdetail'),
                     )

comments/urls.py
from django.conf.urls import patterns,include,url
from . import views

urlpatterns=patterns('',
                     url(r'^$',views.CommentView,name='view'),
                     url(r'^detail/(?P<comment_id>[0-9]+)/$',views.detail,name='detail'),
                     url(r'^detail/(?P<comment_id>[0-9]+)/like/$',views.like,name='like'),
                     url(r'^edit/$', views.CreateCommentView.as_view(success_url="/comments/"),name='edit'),
                     )

hotel/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'',include('mypage.urls', namespace="mypage")),
    url(r'^booking/',include('bill.urls',namespace="booking")),
    url(r'^comments/',include('comments.urls',namespace="comments")),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += staticfiles_urlpatterns()

comments/models.py
from django.db import models
from django.conf import settings
from django.contrib import admin



class Comment (models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL
        )
    title=models.CharField(
        'Заголовок',
        max_length=140
        )
    comment = models.CharField(
        'Отзыв',
        max_length=1000
        )
    date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
        )
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
    

class CommentAdmin(admin.ModelAdmin):
    list_display=('user','date')

class Rating (models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL
        )
    comment=models.ForeignKey(
        Comment,
        verbose_name="Заголовок коментария"
        )
    date = models.DateTimeField(
        'Дата оценки',
        auto_now_add=True
        )
    value=models.IntegerField(
        'Оценка'
        )


    class Meta:
        verbose_name = 'Оценка'
        verbose_name_plural = 'Оценки'

comments/views.py
from django.shortcuts import render,render_to_response,get_object_or_404,redirect
from django.views.generic import ListView,CreateView
from .models import Comment,Rating
from django.db.models import Avg
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse


def CommentView(request):
    comment_list=Comment.objects.all().order_by('-date')
    context={
        'comment_list':comment_list,
        }
    return render(request,'comments/comment-list.html',context)

class CreateCommentView(CreateView):
    template_name='comments/comment-edit.html'
    model=Comment
    fields=['title','comment']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateCommentView, self).form_valid(form)

def detail(request,comment_id):
    comment=get_object_or_404(Comment,pk=comment_id)
    rating=Rating.objects.filter(comment=comment_id).count()
    return render(request, 'comments/detail.html', {'comment': comment,'rating':rating,})

def like(request,comment_id):
    if not Rating.objects.filter(user=request.user,comment_id=comment_id).count():
        like=Rating(user=request.user,comment_id=comment_id,value=1)
        like.save()
        return HttpResponseRedirect(reverse('comments:detail', args=(comment_id,)))
    return HttpResponseRedirect(reverse('comments:detail', args=(comment_id,)))

comments/templates/comments/comment-edit.html
{% extends "comments/comment_base.html" %}
{% block content %}
<h1>Новый отзыв</h1>
{% if user.is_authenticated %}
<form method="POST">
      {% csrf_token  %}
	    {{ form.as_p }}
      <input id="save_comment" type="submit" value="Опубликовать" />
</form>
Ограничение 1000 символов.
{% else %}
<a href="/login">Залогиньтесь</a>
{% endif %}
{% endblock %}

comments/templates/comments/comment-list.html
{% extends "comments/comment_base.html" %}
{% block content %}
<h1>Отзывы пользователей</h1>
{% for comment in comment_list %}
<p />{{ comment.user }}
<br /><a href="/comments/detail/{{ comment.id }}/">{{ comment.title }}</a>
{{ comment.date }}
{% endfor %}
{% endblock %}

comments/templates/comments/comment_base.html
{% extends "base.html" %}
{% block title %}
Отзывы
{% endblock %}
{% block aside %}
<ul>
     <li><a href="{% url 'comments:view' %}">Архив отзывов</a></li>
     <li><a href="{% url 'comments:edit' %}">Написать новый отзыв</a></li>
</ul>
{% endblock %}

comments/templates/comments/detail.html
{% extends "comments/comment_base.html" %}
{% block content %}
<h1>{{ comment.title }}</h1>
автор: {{ comment.user.lastname }} {{ comment.user.firstname }} {{ comment.user.middlename }}
<br />{{ comment.user.email }}
<br />{{ comment.date }}
<br /> Рейтинг: {{ rating }}
<p /><span style="word-wrap:break-word;">{{ comment.comment}}</span>
{% if user.is_authenticated %}
<form action="./like/" method="post">
{% csrf_token %}
<input type="submit" value="Понравилось" />
</form>
{% endif %}
{% endblock %}