bill/urls.py
from django.conf.urls import patterns,include,url
from bill.views import *

urlpatterns=patterns('',
                     url(r'^$',BookingView.as_view(success_url="/mypage/mybookings/"),name='booking'),
                     url(r'^conf/(?P<booking_id>[-0-9]+)/$',ConfirmtheBookingView,name='conf'),
                     url(r'^conf/(?P<booking_id>[-0-9]+)/valid/$',ValidBooking,name='valid'),
                     url(r'^conf/(?P<booking_id>[-0-9]+)/delete/$',DeleteBooking,name='delete'),
                     url(r'^room/(?P<sdate>[-0-9]+)/(?P<edate>[-0-9]+)/$',FindFreeRoom,name='freeroom'),
                     url(r'^room/(?P<sdate>[-0-9]+)/(?P<edate>[-0-9]+)/(?P<style>[a-z]+)/$',FindFreeRoomWS,name='freeroomws'),
                     url(r'^service/$',ServiceOrderView.as_view(success_url="/mypage/myservices/"),name='serviceorder'),
                     url(r'^service/list/$',servicelist,name='servicelist'),
                     url(r'^confservice/(?P<serviceorder_id>[-0-9]+)/$',ConfirmetheServiceOrderView,name='confservice'),
                     url(r'^confservice/(?P<serviceorder_id>[-0-9]+)/valid/$',ValidServiceOrder,name='validservice'),
                     url(r'^confservice/(?P<serviceorder_id>[-0-9]+)/delete/$',DeleteServiceOrder,name='deleteservice'),
                     url(r'^room/(?P<housing>[0-9]+)/(?P<floor>[0-9]+)/(?P<number>[0-9]+)/$',roomdetail,name='roomdetail'),
                     )

comments/urls.py
from django.conf.urls import patterns,include,url
from . import views

urlpatterns=patterns('',
                     url(r'^$',views.CommentView,name='view'),
                     url(r'^detail/(?P<comment_id>[0-9]+)/$',views.detail,name='detail'),
                     url(r'^detail/(?P<comment_id>[0-9]+)/like/$',views.like,name='like'),
                     url(r'^edit/$', views.CreateCommentView.as_view(success_url="/comments/"),name='edit'),
                     )

hotel/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'',include('mypage.urls', namespace="mypage")),
    url(r'^booking/',include('bill.urls',namespace="booking")),
    url(r'^comments/',include('comments.urls',namespace="comments")),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += staticfiles_urlpatterns()

mypage/urls.py
from django.conf.urls import patterns,include,url
from . import views

urlpatterns=patterns('',
                     url(r'^$',views.home_page,name='home'),
                     url(r'^about/$',views.aboutpage,name='about'),
                     url(r'^login/$',views.login_user,name='login'),
                     url(r'^logout/$',views.logout_user,name='logout'),
                     url(r'^registration/$',views.registrate,name='reg'),
                     url(r'^mypage/edit/$',views.profileedit,name='edit'),
                     url(r'^mypage/view/$',views.profileview,name='view'),
                     url(r'^mypage/mybookings/$',views.myBookings,name='mybookings'),
                     url(r'^mypage/myservices/$',views.myServices,name='myservices'),
                     url(r'^mypage/staff/corpbooking/(?P<sdate>[-0-9:]+)/(?P<edate>[-0-9:]+)/(?P<cob>[0-9]+)/$',views.companylist,name='complist'),
                     url(r'^mypage/staff/income/(?P<sdate>[-0-9:]+)/(?P<edate>[-0-9:]+)/$',views.income,name='income'),
                     url(r'^mypage/staff/newusers/(?P<sdate>[-0-9:]+)/(?P<edate>[-0-9:]+)/$',views.newusers,name='newusers'),
                     url(r'^mypage/staff/newusers/detail/(?P<user_id>[0-9]+)/$',views.userdetail,name='userdetail'),
                     url(r'^mypage/addmoney/$',views.addmoney,name='addmoney'),
                     url(r'^mypage/staff/corpbooking/(?P<sdate>[-0-9:]+)/(?P<edate>[-0-9:]+)/(?P<comp_id>[0-9]+)/detail/$',views.compdetail,name='compdetail'),
                     url(r'^mypage/discounts/list/(?P<sdate>[-0-9:]+)/$',views.discountlist,name='discslist'),
                     url(r'^mypage/discounts/detail/(?P<disc_id>[-0-9:]+)/$',views.discountdetail,name='discdetail'),

                     )

mypage/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField,UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib import auth
from django.template import RequestContext
from mypage.models import MpUser


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Подтверждение',
        widget=forms.PasswordInput
    )

    def clean_email(self):
        email=self.cleaned_data["email"]
        try:
            MpUser._default_manager.get(email=email)
        except MpUser.DoesNotExist:
            return email
        raise forms.ValidationError('Такой email уже существует')
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Пароль и подтверждение не совпадают')
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.total_money=0
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields=['email']


class cUserChangeForm(UserChangeForm):

    def __init__( self, *args, **kwargs ):
        super( cUserChangeForm, self ).__init__( *args, **kwargs )
        self.fields['password'] = self.instance.password

    class Meta:
        model = get_user_model()
        fields = ['email', ]

class LoginForm(forms.Form):
    email = forms.CharField(label=u'Email')
    password = forms.CharField(label=u'Пароль', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        if not self.errors:
            user = auth.authenticate(email=cleaned_data['email'], password=cleaned_data['password'])
            if user is None:
                raise forms.ValidationError(u'Имя пользователя и пароль не подходят')
            self.user = user
        return cleaned_data

    def get_user(self):
        return self.user or None

class RegistrationForm(forms.Form):
    login=forms.CharField(label='asd',max_length=100,error_messages={'required': 'Укажите логин'})
    password=forms.CharField(label='Пароль',widget=forms.PasswordInput(),error_messages={'required': 'Укажите пароль'})
    password_again = forms.CharField(label='Пароль (еще раз)',widget=forms.PasswordInput(),error_messages={'required': 'Укажите пароль еще раз'})
    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('password_again'):
            raise forms.ValidationError('Пароли должны совпадать!')
        return self.cleaned_data

class MyPageForm(forms.ModelForm):
  class Meta:
    model = MpUser
    fields=['firstname','middlename','lastname','sex','company','country','city','date_of_birth']

class AddMoneyForm(forms.ModelForm):
    class Meta:
        model=MpUser
        fields=['total_money']

mypage/views.py
from django.shortcuts import render,render_to_response,redirect,get_object_or_404
from django.views.generic import ListView,CreateView
from django.views.generic.edit import FormView
from mypage.forms import LoginForm,RegistrationForm,UserCreationForm,MyPageForm,AddMoneyForm
from django.contrib import auth
from django.http import HttpResponseRedirect,HttpResponse
from .models import MpUser,Company,Contract
from comments.models import Comment,Rating
from bill.models import Booking,Service_order
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.db.models import Count


def home_page(request):
    args={}
    rules=get_object_or_404(Comment,title='Приветствие')
    args['rules']=rules
    comments=Comment.objects.all().order_by('-date')[:5]
    args['top']=comments
    return render(request, 'mypage/index.html',args)

def aboutpage(request):
    args={}
    rules=get_object_or_404(Comment,title='О проекте')
    args['rules']=rules
    comments=Comment.objects.all().order_by('-date')[:5]
    args['top']=comments
    return render(request, 'mypage/index.html',args)

def login_user(request):
    if request.user.is_authenticated():
        return redirect('views.home_page')
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = auth.authenticate(
                email = form.cleaned_data['email'],
                password = form.cleaned_data['password']
            )
            if user is not None:
                auth.login(request, user)
                return HttpResponseRedirect('/')

    return render(request, 'mypage/login.html', {'form': form})

@login_required
def profileedit(request):
    message = 'Your Personal Information has been changed. Thanks!'
    message2 = ':('
    form = MyPageForm(instance = request.user)
    if request.method == 'POST':
        form = MyPageForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return render(request, 'mypage/profile_edit.html', {'form': form,'message': message})
        return render(request, 'mypage/profile_edit.html', {'form': form,'message': message2})
    return render(request, 'mypage/profile_edit.html', {'form': form,})


@login_required
def logout_user(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

def registrate(request):
    args={}
    args.update(csrf(request))
    args['form']=UserCreationForm()
    if request.POST:
        newuser_form=UserCreationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(
                email=newuser_form.cleaned_data['email'],
                password=newuser_form.cleaned_data['password2']
                )
            auth.login(request,newuser)
            return HttpResponseRedirect('/')
        else:
            args['form']=newuser_form
    return render_to_response('mypage/register.html', args)

def profileview(request):
    return render(request,'mypage/view.html')

def myBookings(request):
    if request.user.is_authenticated():
        args={}
        mybookings=Booking.objects.filter(person=request.user).order_by('-pk')
        args['mybookings']=mybookings
        return render(request,'mypage/mybookings.html',args)
    else:
        return HttpResponseRedirect("/login/")

def myServices(request):
    if request.user.is_authenticated():
        args={}
        myso=Service_order.objects.filter(person=request.user).order_by('-pk')
        args['myso']=myso
        return render(request,'mypage/myservices.html',args)
    else:
        return HttpResponseRedirect("/login/")

def companylist(request,cob='0',sdate='2015-01-01 00:00',edate='2051-01-01 00:00'):
    if request.user.is_authenticated():
        if request.user.staff=='manager':
            companylist=Company.objects.all()
            args={}
            args['companylist']=companylist
            cbc={}
            for company in companylist:
                bookings=Booking.objects.filter(company=company).count()
                if bookings>=int(cob):
                    cbc[company]=bookings
            args['cbc']=cbc.items()
            args['sdate']=sdate
            args['edate']=edate
            args['cob']=cob
            return render(request, 'mypage/complist.html',args)
        else:
            return HttpResponse('У данного юзера недостаточно прав для доступа к данной странице.<p> <a href="/">Вернутся на главную страницу</a>')
    else:
        return HttpResponseRedirect("/login/")

def income(request,sdate,edate):
    if request.user.is_authenticated():
        if request.user.staff=='manager':
            args={}
            bookings=Booking.objects.filter(date__range=(sdate,edate)).filter(e_date__range=(sdate,edate),is_delete=False)
            serviceorders=Service_order.objects.filter(date__range=(sdate,edate),is_delete=False)
            incomebookings=0
            incomeserviceorders=0
            for booking in bookings:
                incomebookings+=booking.price
            for serviceorder in serviceorders:
                incomeserviceorders+=serviceorder.price
            args['bookings']=bookings
            args['serviceorders']=serviceorders
            args['ib']=incomebookings
            args['iso']=incomeserviceorders
            args['sdate']=sdate
            args['edate']=edate
            return render(request,'mypage/income.html',args)
        else:
            return HttpResponse('У данного юзера недостаточно прав для доступа к данной странице.<p> <a href="/">Вернутся на главную страницу</a>')

    else:
        return HttpResponseRedirect("/login/")

def newusers(request,sdate,edate):
    if request.user.is_authenticated():
        if request.user.staff=='manager':
            args={}
            newusers=MpUser.objects.filter(register_date__range=(sdate,edate))
            args['sdate']=sdate
            args['edate']=edate
            args['newusers']=newusers
            return render(request,'mypage/newusers.html',args)
        else:
            return HttpResponse('У данного юзера недостаточно прав для доступа к данной странице.<p> <a href="/">Вернутся на главную страницу</a>')
    else:
        return HttpResponseRedirect("/login/")

def userdetail(request,user_id):
    if request.user.is_authenticated():
        if request.user.staff=='manager':
            args={}
            user=get_object_or_404(MpUser,pk=user_id)
            usersbooking=Booking.objects.filter(person=user, is_delete=False)
            usersserviceorders=Service_order.objects.filter(person=user,is_delete=False)
            args['user']=user
            args['ub']=usersbooking
            args['uso']=usersserviceorders
            return render(request,'mypage/userdetail.html',args)
        else:
            return HttpResponse('У данного юзера недостаточно прав для доступа к данной странице.<p> <a href="/">Вернутся на главную страницу</a>')
    else:
        return HttpResponseRedirect("/login/")

def addmoney(request):
    if request.user.is_authenticated():
        user=MpUser.objects.get(pk=request.user.id)
        args={}
        args.update(csrf(request))
        args['form']=AddMoneyForm()
        if request.POST:
            addmoneyform=AddMoneyForm(request.POST, instance = request.user)
            if addmoneyform.is_valid():
                user.total_money=user.total_money+addmoneyform.cleaned_data['total_money']
                user.save()
                return HttpResponseRedirect("/mypage/view/")
        return render_to_response('mypage/addmoney.html', args)
    else:
        return HttpResponseRedirect("/login/")

def compdetail(request,sdate,edate,comp_id):
    comp=get_object_or_404(Company,pk=comp_id)
    if request.user.is_authenticated():
        if request.user.staff=='manager':
            args={}
            comp=get_object_or_404(Company,pk=comp_id)
            bookings=Booking.objects.filter(date__range=(sdate,edate)).filter(e_date__range=(sdate,edate),is_delete=False,company=comp)
            serviceorders=Service_order.objects.filter(date__range=(sdate,edate),is_delete=False,booking_id__company=comp)
            incomebookings=0
            incomeserviceorders=0
            for booking in bookings:
                incomebookings+=booking.price
            for serviceorder in serviceorders:
                incomeserviceorders+=serviceorder.price
            args['ib']=incomebookings
            args['iso']=incomeserviceorders
            args['comp']=comp
            args['bookings']=bookings
            args['serviceorders']=serviceorders
            return render(request,'mypage/compdetail.html',args)
        else:
            return HttpResponse('У данного юзера недостаточно прав для доступа к данной странице.<p> <a href="/">Вернутся на главную страницу</a>')
    else:
        return HttpResponseRedirect("/login/")

def discountlist(request,sdate):
    if request.user.is_authenticated():
        args={}
        discs=Contract.objects.filter(s_date__lte=sdate,is_active=True,company=None).filter(e_date__gte=sdate)
        args['discounts']=discs
        args['sdate']=sdate
        return render(request,'mypage/discslist.html',args)
    else:
        return HttpResponseRedirect("/login/")

def discountdetail(request,disc_id):
    if request.user.is_authenticated():
        args={}
        disc=get_object_or_404(Contract,pk=disc_id)
        args['disc']=disc
        return render(request,'mypage/discdetail.html',args)
    else:
        return HttpResponseRedirect("/login/")

mypage/templates/mypage/compdetail.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
Название: {{ comp.name }}
<br />Страна: {{ comp.country }}
<br />Город: {{ comp.city }}
<br />Почтовый интекс: {{ comp.mailadress }}
<p /> Список активных броней:
{% for booking in bookings %}
<a href="{% url 'booking:conf' booking.id %}">Номер брони: {{ booking.id }}</a>
Заказчик: {{ booking.person }}
<br />Дата заезда: {{ booking.s_date }}
<br />Дата выезда: {{ booking.e_date }}
<br />Номер: {{ booking.room }}
<br />Удалена: {{ booking.is_delete }}
<br />Количество детей: {{ booking.child }}
<br />Количество человек: {{ booking.number_peoples }}
<br />Контракт: {{ booking.contract }}
<br />Дата заказа: {{ booking.date }}
<br />Цена: {{ booking.price }}
{% endfor %}
<p />Доход с броней: {{ ib }}
<p />Список активных заказов дополнительных услуг:
{% for serviceorder in serviceorders %}
<a href="{% url 'booking:confservice' serviceorder.id %}">Номер заказа услуги: {{ serviceorder.id }}</a>
Заказчик: {{ serviceorder.person }}
<br />Услуга: {{ serviceorder.service }}
<br />Бронь: {{ serviceorder.booking }}
<br />Дата заказа: {{ serviceorder.date }}
<br />Стоимость: {{ serviceorder.price }}
<br />Удалена: {{ serviceorder.is_delete }}
{% endfor %}
<p />Доход с заказов дополнительных услуг: {{ iso }}
{% endblock %}

mypage/templates/mypage/complist.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
<h1>Список партнеров и количества их броней, которых больше {{ cob }}, за период с {{ sdate }} по {{ edate }}</h1>
{% for items,value in cbc %}
<a href="{% url 'mypage:compdetail' sdate edate items.id %}">{{ items.name }}</a>
Количество броней: {{ value }}
{% endfor %}
{% endblock %}

mypage/templates/mypage/discdetail.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
<h1>{{ disc.name }}</h1>
Действительна с {{ disc.s_date }} по {{ disc.e_date }}
<br />Скидка на бронирование: {{ disc.booking_discount }}%
<br />Скидка на дополнительные услуги: {{ disc.service_discount }}%
<p /> <a href="{% url 'booking:booking' %}">Перейти на страницу формирования брони</a>
{% endblock %}

mypage/templates/mypage/discslist.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
<h1>Действующие скидки на {{ sdate }}</h1>
{% for disc in discounts %}
<a href="{% url 'mypage:discdetail' disc.contract_number %}">{{ disc.name }}</a>
{% endfor %}
{% endblock %}

mypage/templates/mypage/income.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
<h1>Список броней за период с {{ sdate }} по {{ edate }}</h1>
{% for booking in bookings%}
<a href="{% url 'booking:conf' booking.id %}">Номер брони: {{ booking.id }}</a>
Заказчик: {{ booking.person }}
<br />Дата заезда: {{ booking.s_date }}
<br />Дата выезда: {{ booking.e_date }}
<br />Номер: {{ booking.room }}
<br />Удалена: {{ booking.is_delete }}
<br />Количество детей: {{ booking.child }}
<br />Количество человек: {{ booking.number_peoples }}
<br />Контракт: {{ booking.contract }}
<br />Дата заказа: {{ booking.date }}
<br />Цена: {{ booking.price }}
{% endfor %}
<p />Доход с броней: {{ ib }}
<h1>Список заказов дополнительных услуг за период с {{ sdate }} по {{ edate }}</h1>
{% for serviceorder in serviceorders %}
<a href="{% url 'booking:confservice' serviceorder.id %}">Номер заказа услуги: {{ serviceorder.id }}</a>
Заказчик: {{ serviceorder.person }}
<br />Услуга: {{ serviceorder.service }}
<br />Бронь: {{ serviceorder.booking }}
<br />Дата заказа: {{ serviceorder.date }}
<br />Стоимость: {{ serviceorder.price }}
<br />Удалена: {{ serviceorder.is_delete }}
{% endfor %}
<p />Доход с дополнительных услуг: {{ iso }}
{% endblock %}

mypage/templates/mypage/index.html
{% extends "base.html" %}
{% block content %}
{{ rules.title }}
<p />{{ rules.comment }}
{% endblock %}
{% block aside %}
<h1>5 последних отзывов</h1>
{% for comment in top %}
<p />{{ comment.user }}<br/>
<a href="{% url 'comments:detail' comment.id %}">{{ comment.title }}</a>
Публикация: {{ comment.date }}
{% endfor %}
{% endblock %}

mypage/templates/mypage/login.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
<form action="/login/" method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Войти"/>
</form>
{% endblock %}

mypage/templates/mypage/mybookings.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
{% for booking in mybookings %}
<a href="{% url 'booking:conf' booking.id %}">Номер брони: {{ booking.id }}</a>
Заказчик: {{ booking.person }}
<br />Дата заезда: {{ booking.s_date }}
<br />Дата выезда: {{ booking.e_date }}
<br />Номер: {{ booking.room }}
<br />Удалена: {{ booking.is_delete }}
<br />Количество детей: {{ booking.child }}
<br />Количество человек: {{ booking.number_peoples }}
<br />Контракт: {{ booking.contract }}
<br />Дата заказа: {{ booking.date }}
<br />Цена: {{ booking.price }}
{% endfor %}
{% endblock %}

mypage/templates/mypage/myservices.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
{% for serviceorder in myso %}
<a href="{% url 'booking:confservice' serviceorder.id %}">Номер заказа услуги: {{ serviceorder.id }}</a>
Заказчик: {{ serviceorder.person }}
<br />Бронь: {{ serviceorder.booking }}
<br />Дата заказа: {{ serviceorder.date }}
<br />Цена услуги: {{ serviceorder.price }}
<br />Удалена: {{ serviceorder.is_delete }}
{% endfor %}
{% endblock %}

mypage/templates/mypage/newusers.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
Новые пользователи за период с {{ sdate }} по {{ edate }}
{% for user in newusers %}
<a href="{% url 'mypage:userdetail' user.id %}">{{ user.lastname }} {{ user.firstname }} {{ user.middlename }}</a>
{% endfor %}
{% endblock %}

mypage/templates/mypage/profile_edit.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
<h1>Редактирование профиля</h1>
{% if user.is_authenticated %}
<form method="post" action="{% url 'mypage:edit' %}" class="form-input">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Save"/>
</form>
{% endif %}
{{message}}
{{message2}}
{% endblock %}

mypage/templates/mypage/register.html
{% extends "mypage/mypage_base.html" %}

{% block title %}Регистрация пользователя{% endblock %}

{% block content %}
  <h1>Регистрация пользователя</h1>
   <form action="/registration/" method="post">
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit" value="Отправить" />
   </form>
{% endblock %}

mypage/templates/mypage/userdetail.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
{{ user.lastname }} {{ user.firstname }} {{ user.middlename }}
<br />Адресс электронной почты: {{ user.email }}
<br />Пол: {{ user.sex }}
<br />День рождения: {{ user.date_of_birth }}
<br />Страна: {{ user.country }}
<br />Город: {{ user.city }}
<br />Дата регистрации: {{ user.register_date }}
<br />Статус пользователя: {{ user.staff }}
<p /> Баланс: {{ user.total_money }}
<h1> Список активных броней:</h1>
{% for booking in ub %}
<p />{{ forloop.counter }}. Номер брони: {{ booking.id }}
<br />Заказчик: {{ booking.person }}
<br />Дата заезда: {{ booking.s_date }}
<br />Дата выезда: {{ booking.e_date }}
<br />Номер: {{ booking.room }}
<br />Удалена: {{ booking.is_delete }}
<br />Количество детей: {{ booking.child }}
<br />Количество человек: {{ booking.number_peoples }}
<br />Контракт: {{ booking.contract }}
<br />Дата заказа: {{ booking.date }}
<br />Цена: {{ booking.price }}
{% endfor %}
<h1>Список активных заказов дополнительных услуг:</h1>
{% for serviceorder in uso %}
<p />{{ forloop.counter }}. Номер заказа: {{ serviceorder.id }}
<br />Заказчик: {{ serviceorder.person }}
<br />Услуга: {{ serviceorder.service }}
<br />Бронь: {{ serviceorder.booking }}
<br />Дата заказа: {{ serviceorder.date }}
<br />Стоимость: {{ serviceorder.price }}
<br />Удалена: {{ serviceorder.is_delete }}
{% endfor %}
{% endblock %}

mypage/templates/mypage/view.html
{% extends "mypage/mypage_base.html" %}
{% block content %}
<h1>Мой профиль</h1>
{{ user.lastname }} {{ user.firstname }} {{ user.middlename }}
<br />Адресс электронной почты: {{ user.email }}
<br />Пол: {{ user.sex }}
<br />День рождения: {{ user.date_of_birth }}
<br />Страна: {{ user.country }}
<br />Город: {{ user.city }}
<br />Дата регистрации: {{ user.register_date }}
<br />Статус пользователя: {{ user.staff }}
<p /> Баланс: {{ user.total_money }}
{% endblock %}