bill/urls.py
from django.conf.urls import patterns,include,url
from bill.views import *

urlpatterns=patterns('',
                     url(r'^$',BookingView.as_view(success_url="/mypage/mybookings/"),name='booking'),
                     url(r'^conf/(?P<booking_id>[-0-9]+)/$',ConfirmtheBookingView,name='conf'),
                     url(r'^conf/(?P<booking_id>[-0-9]+)/valid/$',ValidBooking,name='valid'),
                     url(r'^conf/(?P<booking_id>[-0-9]+)/delete/$',DeleteBooking,name='delete'),
                     url(r'^room/(?P<sdate>[-0-9]+)/(?P<edate>[-0-9]+)/$',FindFreeRoom,name='freeroom'),
                     url(r'^room/(?P<sdate>[-0-9]+)/(?P<edate>[-0-9]+)/(?P<style>[a-z]+)/$',FindFreeRoomWS,name='freeroomws'),
                     url(r'^service/$',ServiceOrderView.as_view(success_url="/mypage/myservices/"),name='serviceorder'),
                     url(r'^service/list/$',servicelist,name='servicelist'),
                     url(r'^confservice/(?P<serviceorder_id>[-0-9]+)/$',ConfirmetheServiceOrderView,name='confservice'),
                     url(r'^confservice/(?P<serviceorder_id>[-0-9]+)/valid/$',ValidServiceOrder,name='validservice'),
                     url(r'^confservice/(?P<serviceorder_id>[-0-9]+)/delete/$',DeleteServiceOrder,name='deleteservice'),
                     url(r'^room/(?P<housing>[0-9]+)/(?P<floor>[0-9]+)/(?P<number>[0-9]+)/$',roomdetail,name='roomdetail'),
                     )

hotel/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'',include('mypage.urls', namespace="mypage")),
    url(r'^booking/',include('bill.urls',namespace="booking")),
    url(r'^comments/',include('comments.urls',namespace="comments")),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += staticfiles_urlpatterns()

mypage/urls.py
from django.conf.urls import patterns,include,url
from . import views

urlpatterns=patterns('',
                     url(r'^$',views.home_page,name='home'),
                     url(r'^about/$',views.aboutpage,name='about'),
                     url(r'^login/$',views.login_user,name='login'),
                     url(r'^logout/$',views.logout_user,name='logout'),
                     url(r'^registration/$',views.registrate,name='reg'),
                     url(r'^mypage/edit/$',views.profileedit,name='edit'),
                     url(r'^mypage/view/$',views.profileview,name='view'),
                     url(r'^mypage/mybookings/$',views.myBookings,name='mybookings'),
                     url(r'^mypage/myservices/$',views.myServices,name='myservices'),
                     url(r'^mypage/staff/corpbooking/(?P<sdate>[-0-9:]+)/(?P<edate>[-0-9:]+)/(?P<cob>[0-9]+)/$',views.companylist,name='complist'),
                     url(r'^mypage/staff/income/(?P<sdate>[-0-9:]+)/(?P<edate>[-0-9:]+)/$',views.income,name='income'),
                     url(r'^mypage/staff/newusers/(?P<sdate>[-0-9:]+)/(?P<edate>[-0-9:]+)/$',views.newusers,name='newusers'),
                     url(r'^mypage/staff/newusers/detail/(?P<user_id>[0-9]+)/$',views.userdetail,name='userdetail'),
                     url(r'^mypage/addmoney/$',views.addmoney,name='addmoney'),
                     url(r'^mypage/staff/corpbooking/(?P<sdate>[-0-9:]+)/(?P<edate>[-0-9:]+)/(?P<comp_id>[0-9]+)/detail/$',views.compdetail,name='compdetail'),
                     url(r'^mypage/discounts/list/(?P<sdate>[-0-9:]+)/$',views.discountlist,name='discslist'),
                     url(r'^mypage/discounts/detail/(?P<disc_id>[-0-9:]+)/$',views.discountdetail,name='discdetail'),

                     )

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles%}
    <head>
       <title>{% block title %}Отель "Ласточка"{% endblock %}</title>
	     <meta charset="utf-8">
		 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
		 <link rel="stylesheet" href="{% static 'css/style.css' %}">
		 <script type="text/javascript">
		     function hide(id) {
			     var o=document.getElementById(id).style;
				 if (o.display=='block'){
				 o.display='none';}
				 else{
				 o.display='block';}
				 }
		 </script>
	 </head>
	<body>
	 <header>
	     <div class="left_side" id="left-side">
		         <h1 class="logo_text1">
				     <a href=""><img src="{% static 'images/logo.png' %}" height="50" width="200" alt="logo"></a>
					 <span>Отель "Ласточка"</span>
				 </h1>
	             <div class="left_menu">
		             <ul>
		                 <li><a href="{% url 'mypage:home' %}">Главная</a></li>
				         <li><a href="{% url 'mypage:view' %}">Моя страница</a></li>
						 <li><a href="{% url 'mypage:discslist' '2015-12-18' %}">Акции</a></li>
				         <li><a href="{% url 'comments:view' %}">Отзывы</a></li>
				         <li><a href="{% url 'booking:freeroom' '2015-12-01' '2016-01-01' %}">Свободные номера</a></li>
						 <li><a href="{% url 'booking:booking' %}">Оформление брони</a></li>
						 <li><a href="{% url 'booking:servicelist' %}">Услуги</a></li>
				         <li><a href="{% url 'mypage:about' %}">О проекте</a></li>
				         <br />
						 <br />
						 <br />
						 <br />
						 <span class="logo_text1">Здраствуй, {% if user.is_authenticated %}{{ user.firstname }}{% else %}гость{% endif %}</span>
						 <li>{% if user.is_authenticated %}<a href="{% url 'mypage:logout' %}">Выйти</a>{% else %}<a href="{% url 'mypage:login' %}">Войти</a>{% endif %}</li>
						 <li><a href="{% url 'mypage:reg' %}">Зарегистрироваться</a></li>

					 </ul>
		     </div>
	     </div>
		 <a class="left_swap" onclick="hide('left-side')"></a>
	 </header>
	 <div class="content">
	     <div class="text">
		     <aside>{% block aside %}Правая колонка{% endblock %}</aside>
			 <article>{% block content %}Левая колонка{% endblock %}</article>
	     </div>
	 </div>
	 <footer class="copyright">
    Copyright <a href="http://vk.com/id67368841">Пискунов Андрей</a> {% now "Y" %}г.
	</footer>
	</body>
</html>